# Generated by Django 6.0.1 on 2026-08-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_product_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SizeName', models.CharField(max_length=100, unique=True)),
                ('product_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
